/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp2;

import java.util.ArrayList;
import javax.swing.JPanel;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muhammad Fajar
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    ArrayList<Mobil> listMobil;
    String header[] = new String[]{"No", "Merk", "Plat", "Warna", "Jenis"};
    DefaultTableModel dtm;
    int row,col;
    public main() {
        initComponents();
        listMobil = new ArrayList<>();
        panel_dock.removeAll();
        dtm = new DefaultTableModel(header, 0);
        jTable1.setModel(dtm);
        switchPanel(pan_welcome);
    }
    
    public void switchPanel(JPanel panel){
        panel_dock.removeAll();
        panel_dock.add(panel);
        panel_dock.repaint();
        panel_dock.revalidate();
    }
    
    public void fetchSQLData(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/tp2", "root", "");
            
            String sql = "SELECT * FROM dataMobil";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            Integer i = 0;
            while(rs.next())
            {
                i = i + 1;
                String merk = rs.getString("merk");
                String plat = rs.getString("plat");
                String warna = rs.getString("warna");
                String jenis = rs.getString("jenis");
                dtm.addRow(new Object[]{i, merk, plat, warna, jenis});
            }
            jTable1.setModel(dtm);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void insertData(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/tp2", "root", "");
            
            String sql = "INSERT INTO dataMobil VALUES(NULL, ?, ?, ?, ?)";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            String merk = field_merk.getText();
            String plat = field_plat.getText();
            String warna = field_warna.getText();
            String jenis = cbox_jenis.getSelectedItem().toString();
            pstmt.setString(1, merk);
            pstmt.setString(2, plat);
            pstmt.setString(3, warna);
            pstmt.setString(4, jenis);
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Tersimpan!");
            field_merk.setText("");
            field_plat.setText("");
            field_warna.setText("");
            cbox_jenis.setSelectedIndex(0);
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_header = new javax.swing.JPanel();
        btn_form = new javax.swing.JButton();
        btn_table = new javax.swing.JButton();
        btn_info = new javax.swing.JButton();
        panel_dock = new javax.swing.JLayeredPane();
        pan_form = new javax.swing.JPanel();
        lb_merk = new javax.swing.JLabel();
        field_merk = new javax.swing.JTextField();
        lb_plat = new javax.swing.JLabel();
        field_plat = new javax.swing.JTextField();
        lb_warna = new javax.swing.JLabel();
        field_warna = new javax.swing.JTextField();
        lb_jenis = new javax.swing.JLabel();
        cbox_jenis = new javax.swing.JComboBox<>();
        bt_submit = new javax.swing.JButton();
        pan_table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pan_info = new javax.swing.JPanel();
        lb_nama = new javax.swing.JLabel();
        lb_nim = new javax.swing.JLabel();
        lb_image = new javax.swing.JLabel();
        pan_welcome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pan_top = new javax.swing.JPanel();
        lbl_dataMobil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_header.setBackground(new java.awt.Color(0, 102, 102));

        btn_form.setText("Form");
        btn_form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_formActionPerformed(evt);
            }
        });

        btn_table.setText("Table");
        btn_table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tableActionPerformed(evt);
            }
        });

        btn_info.setText("Info");
        btn_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_infoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_headerLayout = new javax.swing.GroupLayout(panel_header);
        panel_header.setLayout(panel_headerLayout);
        panel_headerLayout.setHorizontalGroup(
            panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_form)
                    .addComponent(btn_table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_headerLayout.setVerticalGroup(
            panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_form)
                .addGap(18, 18, 18)
                .addComponent(btn_table)
                .addGap(228, 228, 228)
                .addComponent(btn_info)
                .addContainerGap())
        );

        panel_dock.setLayout(new java.awt.CardLayout());

        pan_form.setBackground(new java.awt.Color(255, 153, 153));

        lb_merk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_merk.setText("Merk");

        lb_plat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_plat.setText("Plat");

        lb_warna.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_warna.setText("Warna");

        lb_jenis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_jenis.setText("Jenis");

        cbox_jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Biasa", "Balap", "Sport", "Truk" }));

        bt_submit.setText("Submit");
        bt_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan_formLayout = new javax.swing.GroupLayout(pan_form);
        pan_form.setLayout(pan_formLayout);
        pan_formLayout.setHorizontalGroup(
            pan_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_formLayout.createSequentialGroup()
                .addGroup(pan_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pan_formLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pan_formLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(pan_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pan_formLayout.createSequentialGroup()
                                .addComponent(lb_merk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                                .addComponent(field_merk, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pan_formLayout.createSequentialGroup()
                                .addComponent(lb_plat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(field_plat, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_formLayout.createSequentialGroup()
                                .addGroup(pan_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_warna)
                                    .addComponent(lb_jenis))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pan_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(field_warna, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(cbox_jenis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(52, 52, 52))
        );
        pan_formLayout.setVerticalGroup(
            pan_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_formLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pan_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_merk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(field_merk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pan_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_plat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(field_plat, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pan_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_formLayout.createSequentialGroup()
                        .addComponent(lb_warna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_jenis))
                    .addGroup(pan_formLayout.createSequentialGroup()
                        .addComponent(field_warna, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbox_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(bt_submit)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        panel_dock.add(pan_form, "card2");

        pan_table.setBackground(new java.awt.Color(255, 255, 204));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Merk", "Plat", "Warna", "Jenis"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout pan_tableLayout = new javax.swing.GroupLayout(pan_table);
        pan_table.setLayout(pan_tableLayout);
        pan_tableLayout.setHorizontalGroup(
            pan_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_tableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addContainerGap())
        );
        pan_tableLayout.setVerticalGroup(
            pan_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_tableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel_dock.add(pan_table, "card3");

        pan_info.setBackground(new java.awt.Color(204, 255, 204));

        lb_nama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_nama.setText("Muhammad Fajar Yusuf Firdaus");

        lb_nim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_nim.setText("1901581");

        lb_image.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_image.setIcon(new javax.swing.ImageIcon("D:\\FAJAR\\Code\\Java\\TP2\\src\\tp2\\hehe.jpg")); // NOI18N

        javax.swing.GroupLayout pan_infoLayout = new javax.swing.GroupLayout(pan_info);
        pan_info.setLayout(pan_infoLayout);
        pan_infoLayout.setHorizontalGroup(
            pan_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_infoLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(pan_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_nama)
                    .addGroup(pan_infoLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lb_nim)))
                .addGap(125, 125, 125))
            .addGroup(pan_infoLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(lb_image)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pan_infoLayout.setVerticalGroup(
            pan_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_infoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lb_image)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_nama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_nim)
                .addGap(52, 52, 52))
        );

        panel_dock.add(pan_info, "card4");

        pan_welcome.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Selamat Datang ngab");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("TP2 DPBO");

        javax.swing.GroupLayout pan_welcomeLayout = new javax.swing.GroupLayout(pan_welcome);
        pan_welcome.setLayout(pan_welcomeLayout);
        pan_welcomeLayout.setHorizontalGroup(
            pan_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_welcomeLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(pan_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(pan_welcomeLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel2)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        pan_welcomeLayout.setVerticalGroup(
            pan_welcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_welcomeLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        panel_dock.add(pan_welcome, "card5");

        pan_top.setBackground(new java.awt.Color(0, 153, 153));

        lbl_dataMobil.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbl_dataMobil.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dataMobil.setText("DATA MOBIL");

        javax.swing.GroupLayout pan_topLayout = new javax.swing.GroupLayout(pan_top);
        pan_top.setLayout(pan_topLayout);
        pan_topLayout.setHorizontalGroup(
            pan_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_topLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_dataMobil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pan_topLayout.setVerticalGroup(
            pan_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_topLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_dataMobil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_dock)
                    .addComponent(pan_top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pan_top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_dock, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addComponent(panel_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_formActionPerformed
        // TODO add your handling code here:
        switchPanel(pan_form);
    }//GEN-LAST:event_btn_formActionPerformed

    private void btn_tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tableActionPerformed
        // TODO add your handling code here:
        switchPanel(pan_table);
        dtm.setRowCount(0);
        fetchSQLData();
    }//GEN-LAST:event_btn_tableActionPerformed

    private void btn_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_infoActionPerformed
        // TODO add your handling code here:
        switchPanel(pan_info);
    }//GEN-LAST:event_btn_infoActionPerformed

    private void bt_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_submitActionPerformed
        // TODO add your handling code here:
        String merk = field_merk.getText();
        String plat = field_plat.getText();
        String warna = field_warna.getText();
        String jenis = cbox_jenis.getSelectedItem().toString();
        if(merk.length() != 0 && plat.length() != 0 && warna.length() != 0 && jenis.length() != 0){
            insertData();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong!");
        }
    }//GEN-LAST:event_bt_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_submit;
    private javax.swing.JButton btn_form;
    private javax.swing.JButton btn_info;
    private javax.swing.JButton btn_submit;
    private javax.swing.JButton btn_table;
    private javax.swing.JComboBox<String> cb_jenis;
    private javax.swing.JComboBox<String> cbox_jenis;
    private javax.swing.JTextField field_merk;
    private javax.swing.JTextField field_plat;
    private javax.swing.JTextField field_warna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lb_image;
    private javax.swing.JLabel lb_jenis;
    private javax.swing.JLabel lb_merk;
    private javax.swing.JLabel lb_nama;
    private javax.swing.JLabel lb_nim;
    private javax.swing.JLabel lb_plat;
    private javax.swing.JLabel lb_warna;
    private javax.swing.JLabel lbl_dataMobil;
    private javax.swing.JLabel lbl_jenis;
    private javax.swing.JLabel lbl_merk;
    private javax.swing.JLabel lbl_plat;
    private javax.swing.JLabel lbl_warna;
    private javax.swing.JPanel pan_form;
    private javax.swing.JPanel pan_info;
    private javax.swing.JPanel pan_table;
    private javax.swing.JPanel pan_top;
    private javax.swing.JPanel pan_welcome;
    private javax.swing.JLayeredPane panel_dock;
    private javax.swing.JPanel panel_form;
    private javax.swing.JPanel panel_header;
    private javax.swing.JTextField tf_merk;
    private javax.swing.JTextField tf_plat;
    private javax.swing.JTextField tf_warna;
    // End of variables declaration//GEN-END:variables
}
